# Generated by Django 5.2 on 2026-01-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('real_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('identity', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('position_index', models.CharField(max_length=255)),
                ('publish_location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='admin_role.admin')),
            ],
            options={
                'db_table': 'admin_notice_copy1',
            },
        ),
    ]
