"""
Django settings for IBWeb project.

Generated by 'django-admin startproject' using Django 5.1.3.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# DANGER: In a production environment, never hardcode the secret key!
# It's better to load it from an environment variable.
# Example: SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
SECRET_KEY = "django-insecure-i!0^dkxac6l6y-oltm5g=no@f(-ads&fov(8v0#1xl=dt9jbph"

# DANGER: In a production environment, DEBUG must be set to False!
# It's better to load this from an environment variable as well.
DEBUG = True

# SECURITY FIX: Using ['*'] is insecure. For development, it's safer
# to specify local hosts. For production, list your actual domain(s).
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ucsib45.com', '106.12.187.79']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Recommended to add Django's built-in admin site
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'admin_role.apps.AdminRoleConfig'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",  # It's not recommended to remove this
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "IBWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "IBWeb.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'python_scene',
        'USER': 'root',
        # DANGER: In a production environment, never hardcode passwords!
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i1n/

# You can change this to 'zh-hans' for Chinese
LANGUAGE_CODE = "en-us"

# Consolidated the timezone settings here for clarity
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# Keeping USE_TZ = True is a best practice for handling timezones correctly
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
