"""
Django settings for IBWeb project.

Generated by 'django-admin startproject' using Django 5.1.3.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# DANGER: 生产环境中绝不能硬编码密钥！建议从环境变量中读取。
# 例如: SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
SECRET_KEY = "django-insecure-i!0^dkxac6l6y-oltm5g=no@f(-ads&fov(8v0#1xl=dt9jbph"

# DANGER: 生产环境中绝不能开启 DEBUG 模式！
# 建议从环境变量中读取，例如: DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
DEBUG = True

# 安全修复：避免使用 ['*']，因为它会带来安全风险。
# 在开发环境中，使用下面的配置更安全。生产环境中应填写您的域名。
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # 建议加回 Django 自带的后台管理应用
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'admin_role.apps.AdminRoleConfig'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # 安全建议：不建议移除此中间件
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "IBWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "IBWeb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'python_scene',
        'USER': 'wuyufeng',
        # DANGER: 生产环境中密码也应该从环境变量读取
        'PASSWORD': 'wuyufeng',
        'HOST': '192.168.0.166',
        'PORT': 3306,
        # 错误修复：移除了导致 TypeError 的 OPTIONS 配置。
        # 'OPTIONS': {
        #     'client_flag': 'CLIENT_SECURE_CONNECTION',
        # }
    }
}

# 之前在 DEBUG 判断中移除 CSRF 中间件的逻辑已删除，因为这通常是不安全的做法。
# 如果需要对特定视图禁用 CSRF，请使用 @csrf_exempt 装饰器。

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us" # 或 "zh-hans"

# 代码整理：将时区相关的设置集中在这里
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True # 保持 True 是最佳实践，让 Django 处理时区


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"